### ISSUE TITLE
Dose not to let us upgrade the plugin, Craft 3.4 PHP 7.2.

### ISSUE THREAD

**Issue by green17** [percipioglobal/craft-password-policy#13]
Dose not to let us upgrade the plugin, Craft 3.4 PHP 7.2.

Does it need a higher PHP version?

**Comment by michtio** [comment]
Could you provide more information / log output. There is no PHP restriction set and should work from PHP 7.0 and higher

**Comment by green17** [comment]
Doing it on a few sites, great plugin. 

**When running an update all other plugins/craft updated we get this:**

Composer output: Package "craftcms/vue-asset" listed for update is not installed. Ignoring.
Package "danielstjules/stringy" listed for update is not installed. Ignoring.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

Problem 1
- dragonbe/hibp v0.1.1 requires php >= 7.2 -> your PHP version (7.2.31-1+devuan1~1) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
- dragonbe/hibp v0.1.0 requires php >= 7.2 -> your PHP version (7.2.31-1+devuan1~1) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
- percipioglobal/craft-password-policy 1.0.6 requires dragonbe/hibp ^0.1.0 -> satisfiable by dragonbe/hibp[v0.1.0, v0.1.1].
- Installation request for percipioglobal/craft-password-policy 1.0.6 -> satisfiable by percipioglobal/craft-password-policy[1.0.6].

**Comment by fThues** [comment]
Just tried installing the plugin for the first time and ran into the same issue.

**Comment by michtio** [comment]
@fThues do you remember on which environment that happened?
Going to try and replicate some different environments this week, but my biggest guess is that culprit is the "hibp" library, it hasn't been updated for a long time.
