### ISSUE TITLE
if enabled, user activation fails

### ISSUE THREAD

**Issue by emagine** [percipioglobal/craft-password-policy#14]
As above, craft 3.6.0 and the latest version of this plugin, throws an error on user activation email after registration.  

`Interface 'Psr\Http\Client\ClientInterface' not found. The error is coming from the ricardofiorani/guzzle-psr18-adapter vendor files...`

Thinking the error is not displaying at that point if the password is not strong enough to pass the rules, but it falls over.

**Comment by cookie10codes** [comment]
Thanks for posting your issue. We will have a look this week 👍🏼

**Comment by cookie10codes** [comment]
Hi @emagine, we can't replicate the issue. Could you send us you composer.json file? You can email me if you like, stefanie@percipio.london
